---
framework: mocha
postmerge:
  pattern:
    - "test/app.locals.js"
  strategy:
    threshold: <5|100s|30m|6h>
    type: <commit|time>
premerge:
  - "test/app.locals.js"
prerun:
  - npm install
postrun:
  - node --version
version: 2.0